# NumPy - Numerical Python

## Advantages of Numpy Arrays:

- **Allows several Mathematical Operations**: NumPy provides a comprehensive mathematical framework that allows for a wide range of mathematical operations on arrays. It supports basic arithmetic, complex mathematical functions, linear algebra, statistical operations, and much more.

- **Faster operations**: NumPy arrays are implemented in C and optimized for performance. This makes operations on NumPy arrays much faster compared to standard Python lists, especially as the size of the data grows. This speedup is achieved through vectorization, which allows for batch operations on data without the need for explicit looping.


In [1]:
import numpy as np

List vs Numpy - Time Taken

In [4]:
# process_time used to calculate the time for a particular process
from time import process_time

Time taken by a list

In [5]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0015754399999998725


In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.000656311000000187


#Numpy Arrays

In [7]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

An array is a data structure that stores a collection of items. These items are typically of the same data type, such as integers, floats, or strings. Python's built-in array module can create and manipulate compact arrays of basic data types, but it is somewhat limited in functionality.

In [9]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a.shape

(4,)

In [11]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [14]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [17]:
# create an identity matrix
a = np.eye(5)
print(a)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.43085684 0.81199707 0.8047187  0.78015893]
 [0.22954481 0.3002529  0.26005969 0.63810085]
 [0.92611757 0.23129847 0.12573847 0.95004598]]


In [19]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)


[[25 72 70 67 89]
 [59 30 12 64 48]
 [64 51 63 73 12]]


In [20]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [21]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)


[10 15 20 25]


In [22]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [23]:
c = np.random.randint(10,90,(5,5))
print(c)

[[60 63 48 50 81]
 [24 32 50 61 18]
 [69 75 51 45 52]
 [35 63 77 24 59]
 [58 62 68 29 84]]


In [24]:
# array dimension
print(c.shape)

(5, 5)


In [25]:
# number of dimensions
print(c.ndim)

2


In [26]:
# number of elements in an array
print(c.size)

25


In [27]:
# checking the data type of the values in the array
print(c.dtype)


int64


In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [29]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [30]:
print(a)
print(b)

[[0 3 8]
 [3 5 8]
 [2 5 1]]
[[18 19 16]
 [18 14 10]
 [13 12 18]]


In [31]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 22 24]
 [21 19 18]
 [15 17 19]]
[[-18 -16  -8]
 [-15  -9  -2]
 [-11  -7 -17]]
[[  0  57 128]
 [ 54  70  80]
 [ 26  60  18]]
[[0.         0.15789474 0.5       ]
 [0.16666667 0.35714286 0.8       ]
 [0.15384615 0.41666667 0.05555556]]


In [32]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [33]:
print(a)
print(b)

[[5 7 4]
 [1 1 7]
 [2 7 2]]
[[19 16 15]
 [16 15 14]
 [13 12 19]]


In [34]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[24 23 19]
 [17 16 21]
 [15 19 21]]
[[-14  -9 -11]
 [-15 -14  -7]
 [-11  -5 -17]]
[[ 95 112  60]
 [ 16  15  98]
 [ 26  84  38]]
[[0.26315789 0.4375     0.26666667]
 [0.0625     0.06666667 0.5       ]
 [0.15384615 0.58333333 0.10526316]]


In [35]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 5 2]
 [5 2 2]]
(2, 3)


In [36]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[4 5]
 [5 2]
 [2 2]]
(3, 2)


In [37]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 4 1]
 [5 7 2]]
(2, 3)


In [38]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 5]
 [4 7]
 [1 2]]
(3, 2)


In [39]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 3 3]
 [8 3 7]]
(2, 3)


In [40]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 3]
 [3 8]
 [3 7]]
(3, 2)
